---
abstract: 'minimal try/catch with proper preservation of $@'
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
  - 'Jesse Luehrs <doy@tozt.net>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.88
  if: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Try-Tiny
provides:
  Try::Tiny:
    file: lib/Try/Tiny.pm
    version: 0.19
requires:
  Carp: 0
  Exporter: 5.57
  constant: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doy/try-tiny/issues
  homepage: http://metacpan.org/release/Try-Tiny
  repository: git://github.com/doy/try-tiny.git
version: 0.19
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@DOY/GatherDir'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@DOY/PruneCruft'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@DOY/ManifestSkip'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@DOY/MetaYAML'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::License
      name: '@DOY/License'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@DOY/Readme'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@DOY/RunExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@DOY/ExecDir'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@DOY/ShareDir'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@DOY/MakeMaker'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@DOY/Manifest'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@DOY/TestRelease'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@DOY/ConfirmRelease'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@DOY/MetaConfig'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@DOY/MetaJSON'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@DOY/NextRelease'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@DOY/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@DOY/PkgVersion'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@DOY/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@DOY/PodCoverageTests'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@DOY/PodSyntaxTests'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@DOY/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@DOY/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@DOY/Test::Compile'
      version: 2.021
    -
      class: Dist::Zilla::Plugin::Metadata
      name: '@DOY/Metadata'
      version: 3.03
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@DOY/MetaResources'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@DOY/Git::Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@DOY/Git::Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@DOY/Git::Tag'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@DOY/Git::NextVersion'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@DOY/ContributorsFromGit'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@DOY/MetaProvides::Package'
      version: 1.14000003
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@DOY/PodWeaver'
      version: 3.101642
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@DOY/UploadToCPAN'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: ContributorsFromGit
      version: 0.006
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 5.012
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: recommends
      name: TestRecommends
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: 5.012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: 5.012
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.012
x_authority: cpan:NUFFIN
x_contributors:
  - 'Alex <alex@koban.(none)>'
  - 'Andrew Yates <ayates@haddock.local>'
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>'
  - 'Glenn Fowler <cebjyre@cpan.org>'
  - 'Graham Knop <haarg@haarg.org>'
  - 'Hans Dieter Pearcey <hdp@weftsoar.net>'
  - 'Jonathan Yu <JAWNSY@cpan.org>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Marc Mims <marc@questright.com>'
  - 'Mark Fowler <mark@twoshortplanks.com>'
  - 'Mark Stosberg <mark@stosberg.com>'
  - 'Paul Howarth <paul@city-fan.org>'
  - 'Peter Rabbitson <ribasushi@cpan.org>'
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'anaxagoras <walkeraj@gmail.com>'
  - 'awalker <awalker@sourcefire.com>'
  - 'chromatic <chromatic@wgz.org>'
